name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    steps:
      - uses: actions/checkout@v3
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: Debajit91
          UTC_OFFSET: 6
