name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *" # every day 00:00 UTC
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: Debajit91
